{{- if .Values.otel.enabled }}
{{- if .Values.otel.deployJaeger }}
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  ports:
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
  selector:
    {{- include "podinfo.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{- end }}
{{- end }}
